server {
    listen 80;

    # Frontend de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Reverse Proxy al Backend
    location /api {
        proxy_pass http://backend:3000;
    }
}