version: '3.8'

services:
  # Servicio Backend
  backend:
    image: adriandiaz24/smartmark-backend:latest
    container_name: smartmark-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://frontend
      - PORT=3000
      - DATABASE_PATH=/app/src/database/smartmark.db #
      - JWT_SECRET=dasdadwadasfwadfwaf45486d4a86d5a
      - JWT_EXPIRE=7d
      - VERIFICATION_INTERVAL=604800000
      - MAX_FILE_SIZE_MB=5
      - HTTP_TIMEOUT=5000
    volumes:
      - smartmark-db:/app/src/database
      - smartmark-uploads:/app/uploads
    networks:
      - smartmark-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://backend:3000/api/links"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servicio Frontend
  frontend:
    image: adriandiaz24/smartmark-frontend:latest
    container_name: smartmark-frontend
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_BASE_URL=/api
    depends_on:
      - backend
    networks:
      - smartmark-network
    restart: unless-stopped

networks:
  smartmark-network:
    driver: bridge

volumes:
  smartmark-db:
  smartmark-uploads:
